Feature: Training skills and Fight columns for NPCs
MWSE/MWSE pull request #520
Opened 2024-04-27 04:31 UTC by ManProgramming

## Overview
There was a request to add these two columns on the Tamriel Rebuilt discord to help NPCers. The two columns are Training Skills and Fight:

- **Training Skills:** For any NPC who offers training, the Training column lists the NPC's three trainable skills with the levels in parentheses
- **Fight:** Fight column indicates the NPC's fight level

I don't really know much about MWSE and my C++ is rusty so I'm just trying to understand what I can improve on and fix on this PR to get it ready.

## CSSE Application

In practice these two columns look like this:
![image](https://github.com/MWSE/MWSE/assets/24998770/d3081c0c-04f9-4f07-bf4d-5db7044f8a95)

There is also filtering for the Training skills column
![image](https://github.com/MWSE/MWSE/assets/24998770/893ad105-980b-4cea-a5e8-f2af85a38724)

2024-06-02 09:04 UTC, NullCascade requested changes
Sorry for taking so long to get back on this. I really appreciate the contribution here. I have some notes so that skill names are not hardcoded, and to try to speed up searching on this data. Please let me know if you have any questions.

2024-06-02 09:04 UTC, NullCascade commented on CSSE/CSNPC.cpp
> +	const char* NPC::getSkillName(int skillIndex) const {
This hardcoded list can be changed to read from the GMSTs. You can use `RecordHandler::getGameSettingForSkill` to access the value. For example:
```cpp
const auto recordHandler = DataHandler::get()->recordHandler;
const auto skillName = recordHandler->getGameSettingForSkill(skill->skillID);
```

2025-04-29 23:07 UTC, ManProgramming commented on CSSE/CSNPC.cpp
> +	const char* NPC::getSkillName(int skillIndex) const {
Done, made it such that the getGameSettingsForSkill is used in order to get the skill name

2025-04-30 05:35 UTC, ManProgramming commented on CSSE/CSNPC.cpp
> +	std::string NPC::getTraining() const {
Update to use the char buffer. And yeah that is a huge improvement in the initial load time! Also refactored the filtering to follow the new class search approach

2025-06-07 09:10 UTC, merged

2025-06-07 09:11 UTC, NullCascade commented
Thanks for the contribution! Sorry for taking so long to get back to you, again.